ROX-22106: Move automation-flavor image version to a Chart annotation
stackrox/infra pull request #1203
Opened 2024-02-29 15:09 UTC by tommartensen

This will make it easier to update the image versions consistently.

2024-03-01 17:34 UTC, gavin-stackrox requested changes
Lets discuss in Slack. Having all infra flavors using the same automation-flavor presents some challenges.

2024-03-04 17:06 UTC, tommartensen commented
Agreement in team sync: @tommartensen does a manual smoke test for all flavors before merging this PR.

2024-03-05 09:17 UTC, tommartensen commented on .github/workflows/smoke-test.yaml
> +        uses: stackrox/actions/infra/create-cluster@tm/create-cluster-endpoint
Change to `v1` when https://github.com/stackrox/actions/pull/48 is merged

2024-03-06 17:58 UTC, gavin-stackrox approved these changes
LGTM! `static` should be renamed now right?

2024-03-07 07:07 UTC, tommartensen commented
> static should be renamed now right?

eventually maybe.

2024-03-07 07:07 UTC, merged