ROX-15587: Add basic Prometheus metrics
stackrox/infra pull request #1220
Opened 2024-03-11 16:16 UTC by BradLugo

## Description

Implements the following custom Prometheus metrics:

- Counter for flavors used

2024-03-11 17:11 UTC, BradLugo commented
Tested via:
```
❯ nohup kubectl -n infra port-forward svc/infra-server-service 8443:8443 &
[1] 55446
appending output to nohup.out
❯ curl --insecure https://localhost:8443/metrics
... # gRPC and HTTP metrics

# HELP infra_flavors_used Kubernetes cluster flavors being created
# TYPE infra_flavors_used counter
infra_flavors_used{flavor="simulate"} 7
infra_flavors_used{flavor="test-connect-artifact"} 1
infra_flavors_used{flavor="test-hello-world"} 5
infra_flavors_used{flavor="test-qa-demo"} 7

# gRPC and HTTP metrics
...
```

After provisioning a `gke-default` cluster:
```
❯ curl --insecure https://localhost:8443/metrics
... # gRPC and HTTP metrics

# HELP infra_flavors_used Kubernetes cluster flavors being created
# TYPE infra_flavors_used counter
infra_flavors_used{flavor="gke-default"} 1
infra_flavors_used{flavor="simulate"} 7
infra_flavors_used{flavor="test-connect-artifact"} 1
infra_flavors_used{flavor="test-hello-world"} 5
infra_flavors_used{flavor="test-qa-demo"} 7

# gRPC and HTTP metrics
...
```

2024-03-11 17:13 UTC, tommartensen requested changes
I'm blocking this because the metrics are publicly accessible without authentication. The metrics themselves look ok.

2024-03-12 12:05 UTC, tommartensen requested changes
some thoughts.

2024-03-12 12:05 UTC, tommartensen commented on service/cluster/cluster.go
> +	metrics.FlavorsUsedCounter.WithLabelValues(flav.ID).Inc()
IMHO this should be moved to after the `s.argoWorkflowsClient.CreateWorkflow()` call, where we handle the other post-workflow creation actions, like logging, BigQuery integration.

2024-03-12 14:00 UTC, tommartensen commented
> I'm blocking this because the metrics are publicly accessible without authentication. The metrics themselves look ok.

Addressed in #1222 .

2024-03-13 07:49 UTC, tommartensen approved these changes
LGTM to me with one typo suggestion

2024-03-13 07:49 UTC, tommartensen commented on service/metrics/metrics.go
> +			Help:      "Number of cluster created by flavor",
```suggestion
			Help:      "Number of clusters created by flavor",
```

sorry for not spotting earlier / providing wrong suggestion.

2024-03-13 08:48 UTC, merged